<?php
/**
 * Created by PhpStorm.
 * User: 1
 * Date: 17.11.2017
 * Time: 19:53
 */

require_once "Form.php";

class SmartForm extends Form
{
    protected function prepareAttr(array $attr)
    {
        if (isset($attr['name'])
            && !isset($attr['value'])
            && isset($_REQUEST[$attr['name']])
        ) {
            $attr['value'] = $_REQUEST[$attr['name']];
        }
        return parent::prepareAttr($attr); // TODO: Change the autogenerated stub //CTRL O
    }

}